<div class="cube1">
	<form method="post">
		<!-- e-mail -->
		<div>
			<label for="aliasemail">Adresse e-mail :</label>
				<input id="aliasemail" type="text" name="email" placeholder=""/>
		</div>
		<!-- password -->
		<div>
			<label for="aliasmdp">Password :</label>
		    <input id= "aliasmdp" type="password" name="mdp"/>
		</div>
		<!-- Connexion -->
		<div>
			<button type="submit">Connexion</button>
		</div>
	</form>
</div>