<div class="cube1">
	<form method="post">	
    	<!-- Login -->
    	<div>
    		<label for="aliaslogin">Login :</label>
    		<input id="aliaslogin" type="text" name="login" placeholder=""/>
		</div>
		<!-- e-mail -->
		<div>
			<label for="aliasemail">Adresse e-mail :</label>
				<input id="aliasemail" type="text" name="email" placeholder=""/>
		</div>
		<!-- password -->
		<div>
				<label for="aliasmdp">Password :</label>
			    <input id="aliasmdp" type="password" name="mdp"/>
		</div>
		<!-- confirm.password -->
		<div>
				<label for="aliascmdp">Confirm.Password :</label>
			    <input id="aliascmdp" type="password" name="cmdp"/>
		</div>
		
		<!-- valid -->
		<div>
			<button type="submit">Envoyer</button>
		</div>
	</form>
</div>